
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka
    component: kafka-connector
  name: kafka-connector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        component: kafka-connector
    spec:
      containers:
      - name: kafka
        image: alexellis2/kafka-connector:0.2.1
        env:
          - name: gateway_url
            value: "http://gateway.openfaas:8080"
          - name: topics
            value: "faas-request,"
          - name: print_response
            value: "true"
